services:
  triademo.api:
    image: triademo.api
    build:
      context: .
      dockerfile: TriaDemo.Api/Dockerfile
    ports:
      - 5000:8080
  
  db:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: mystrongpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgresserver
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 5001:8080