services:
  triademo.restapi:
    image: triademo-restapi
    build:
      context: .
    ports:
      - 5000:8080
    depends_on:
      - triademo.database
  
  triademo.database:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: mystrongpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgresserver
    ports:
      - 5432:5432
